### ISSUE TITLE
Can't load dataset while executing "main_FineTuneWav2Vec_CV.py"

### ISSUE THREAD

**Issue by Marnhiar** [cristinalunaj/MMEmotionRecognition#8]
I tried to execute "main_FineTuneWav2Vec_CV.py" but got interrupted because of this exception. Can anyone help me with this please?

Generating validation split: 0 examples [00:00, ? examples/s]Traceback (most recent call last):
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\builder.py", line 1777, in _prepare_split_single
    writer.write_table(table)
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\arrow_writer.py", line 552, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\table.py", line 2110, in table_cast
    return cast_table_to_schema(table, schema)
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\table.py", line 2071, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
name: null
path: null
emotion: null
actor: null
__index_level_0__: null
-- schema metadata --
pandas: '{"index_columns": ["__index_level_0__"], "column_indexes": [{"na' + 762
to
{'name': Value(dtype='string', id=None), 'path': Value(dtype='string', id=None), 'emotion': Value(dtype='string', id=None), 'actor': Value(dtype='int64', id=None)}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/Audio/FineTuningWav2Vec/main_FineTuneWav2Vec_CV.py", line 260, in <module>
    dataset = load_dataset("csv", data_files=data_files, delimiter="\t", )
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\load.py", line 1747, in load_dataset
    num_proc=num_proc,
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\builder.py", line 826, in download_and_prepare
    **download_and_prepare_kwargs,
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\builder.py", line 913, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\builder.py", line 1651, in _prepare_split
    {"gen_kwargs": gen_kwargs, "job_id": job_id, **_prepare_split_args}
  File "D:\Speech Emotion Recognition\Env\lib\site-packages\datasets\builder.py", line 1795, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

**Comment by LonyAi55** [comment]
I use this paper mentioned datasets.Do you use Ffmpeg  to process your dataset? I think maybe you change the name of your dataset.I guess.

**Comment by min-program** [comment]
I have the same problem.
Does anyone know a solution?
